### ISSUE TITLE
Created workshop item returns the wrong ID

### ISSUE THREAD

**Issue by cozyGalvinism** [Noxime/steamworks-rs#100]
Okay so this is a weird issue and I will try and look further into it, but the gist of it is the following:

I'm using steamworks-rs to create and upload workshop items. In general, this works alright, except for a glaring issue: If you create a workshop item with `ugc.create_item`, it will return the wrong ID for the created workshop item.

**Example:**
I created an item, I get the following from my callback handler:
![image](https://user-images.githubusercontent.com/1332113/172471368-c200071e-2164-40ec-a7fc-b5b41b8d0098.png)
Okay, looks sane, even though the ID is a little bit... high, but whatever. Now, checking out the newly created workshop item in Steam shows the following ID:
![image](https://user-images.githubusercontent.com/1332113/172471521-b461b351-31a8-4f26-806a-f3d5982484d8.png)

I have no idea if this only happens on my machine or if something else is going on. I will run some tests on other machines and add some logging...

Maybe someone already encountered this and can tell me what's going on.

**Comment by cozyGalvinism** [comment]
Okay, so Steam creates it with the correct ID, at least according to the log at `Steam/logs/workshop_log.txt`, leaving me to believe there's either something wrong with the bindings themselves or it's a communication issue between the Steam API and my application.

**Comment by ceifa** [comment]
The current `bindings.rs` runs the last steamworks sdk version `153a` since https://github.com/Noxime/steamworks-rs/pull/79
I'm a little bit confused about what you did to fix. Can you explain better? Feel free to open a PR too.

**Comment by cozyGalvinism** [comment]
To fix, I literally just cloned the repo, cded into `steamworks_sys` and ran `cargo build --features rebuild-bindings`.

**Comment by ceifa** [comment]
That is weird. But anyway, if it fixed the problem, you can open a PR :)
@james7132 any thoughts on that?

**Comment by james7132** [comment]
If updating the bindings fixes it, I see no reason to question the change. We should be regularly keeping the bindings and SDK binaries up to date.

**Comment by cozyGalvinism** [comment]
So this bug is likely a result of not using platform-specific bindings, meaning it should resolved with #106 .
