### ISSUE TITLE
Need help for start with API

### ISSUE THREAD

**Issue by Avocadocs** [Noxime/steamworks-rs#101]
Hello, I recently started to use this API and I would like upload workshop item but I don't get what is &self arg and cb arg. If you could send me full example... Thanks!

**Comment by cozyGalvinism** [comment]
This is how you create the item:
```rust
    pub fn create_workshop_item(client: &steamworks::Client) {
        let ugc = client.ugc();
        // replace the app id with yours
        ugc.create_item(steamworks::AppId(480), steamworks::FileType::Community, |r| {
            // r contains the result
        });
    }
```

Though I advise you to read the Steamworks SDK documentation in order to understand how this process really works, as there is more to it. This crate is only a wrapper around the bindings so far and isn't comparable to Facepunch.Steamworks.

**Comment by Avocadocs** [comment]
Thank you so much, yeah I will look into steamworks sdk doc but I'm also new to rust so some things are confusing me...

**Comment by cozyGalvinism** [comment]
@Avocadocs You can see my take on an example in #103 . It should cover most of the use-cases, though you will have to make sure you only upload the item content if it has actually been created. Additionally, you might encounter #100 , though I have also issued a PR for an update on the bindings to fix this.

**Comment by Avocadocs** [comment]
Thank you so much everything is fine except when I add this parameter `.preview_path(Path::new("C:\\Users\\Elève\\Desktop\\Utile\\Icons\\python.png"))` upload is working but not update, this is weird because if I remove it i'm abble to change desc, title, content so it's weird

**Comment by Avocadocs** [comment]
So I verified and file is less than 1MB (around 217ko) and files exists, if I past path in file explorer it open file... But I don't get error, where I am supposed to look for see error ?
