### ISSUE TITLE
[Proposal] Change callback API to work without keeping in a variable

### ISSUE THREAD

**Issue by ceifa** [Noxime/steamworks-rs#124]
I don't think we should have comments likes this:
https://github.com/Noxime/steamworks-rs/blob/30904ebe88d1accb66fa840f92776ea1fd50a314/examples/chat-example/src/main.rs#L58-L62

As a proposal to the API, I think the callback should only be dropped when explicite requested, so we don't have unexpected cases where our callbacks stop working from nothing.

Related: https://github.com/ceifa/steamworks.js/issues/77

**Comment by Noxime** [comment]
I agree. It's not intuitive and not very rusty. Explicit unregister_callback works better.

I have been thinking of combing through everything someday and rewriting the APIs to be easier to use. At the same time we should hit 100% API coverage, but I've just been struggling to find time for it.

**Comment by james7132** [comment]
I've run into something tangentially related, but I have an API suggestion in #125 that might also resolve this problem too.

**Comment by ceifa** [comment]
@james7132 do you think both can live together? I think the current API would be more productive for my use case.
