### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by kristoff3r** [Noxime/steamworks-rs#145]
Hi,

Thanks for the work so far on this crate. I'm about to use it (mostly the networking parts) for some work related stuff and I'm making some improvements that I would like to upstream. I can see that there is already a bit of a backlog, i.e. some good PRs that haven't been merged and some improvements on master that haven't been released. Before I split up my changes into PR sized chunks I wanted to hear if there are capacity to review/merge stuff?

I'm happy to help maintaining as well.

**Comment by Noxime** [comment]
Hey,

Thanks for the concern. I do recognize the crate is in bit of a maintance trouble. While I can't speak for other collaborators, I personally haven't had much time to work on OSS projects recently and things have fallen behind. It's an unfortunate situation, but not much I can do about. 

If you are interested in becoming a maintainer I am very happy to add you as a collaborator. Steamworks-rs (afaik) is still the de facto crate for accessing steam services for Rust games, and should stay alive.

**Comment by kristoff3r** [comment]
> Hey,
> 
> Thanks for the concern. I do recognize the crate is in bit of a maintance trouble. While I can't speak for other collaborators, I personally haven't had much time to work on OSS projects recently and things have fallen behind. It's an unfortunate situation, but not much I can do about.
> 
> If you are interested in becoming a maintainer I am very happy to add you as a collaborator. Steamworks-rs (afaik) is still the de facto crate for accessing steam services for Rust games, and should stay alive.

No worries, I'll start doing some PRs then. I'd be happy to help maintain, just send me an invite.

**Comment by lucaspoffo** [comment]
Hey @kristoff3r @Noxime,

Sorry for the ping. Is there any plan for a new version release? There is a lot of cool stuff that's been merged.

I want to release [renet_steam](https://github.com/lucaspoffo/renet/tree/master/renet_steam), a transport layer for `renet` that uses `steamwork-rs,` but I do depend on a few unreleased APIs.

**Comment by kristoff3r** [comment]
@lucaspoffo I think a release sounds like a good idea. I don't know who (if any) apart form @Noxime that has credentials for crates.io, so I can't do it yet unfortunately.

**Comment by Noxime** [comment]
> @lucaspoffo I think a release sounds like a good idea. I don't know who (if any) apart form @Noxime that has credentials for crates.io, so I can't do it yet unfortunately.

I am up for a new release, it's been a while. Are there any outstanding PRs or issues we should resolve before a new crates.io release?

**Comment by kristoff3r** [comment]
> > @lucaspoffo I think a release sounds like a good idea. I don't know who (if any) apart form @Noxime that has credentials for crates.io, so I can't do it yet unfortunately.
> 
> I am up for a new release, it's been a while. Are there any outstanding PRs or issues we should resolve before a new crates.io release?

@Noxime I don't think so, let's just do a release now and then we can do an SDK update and merge my stuff after.
