### ISSUE TITLE
error: failed to run custom build command for `steamworks-sys v0.7.0`

### ISSUE THREAD

**Issue by cybermancy** [Noxime/steamworks-rs#51]
I have followed the instructions for the requirements. I'm not sure what i'm doing wrong.

**Comment by cybermancy** [comment]
I believe the problem has come from not installing steamworks correctly. My env is linux 64bit and I have run the setup.sh script that came in the steamworks/sdk/tools/ folder. Is it installed now? Do I need to build something with clang? Which folder do I set the env var to?

**Comment by Noxime** [comment]
Hello

After extracting the SDK zip archive from [the steamworks page](https://partner.steamgames.com/doc/sdk) the resulting folder should be just called `sdk/`. You can point to the right directory with the command `$ export STEAM_SDK_LOCATION=$HOME/Downloads/sdk` (assuming you unzipped the sdk to the Downloads directory).

After this (and possibly a `cargo clean`) everything should work seamlessly. If you have more trouble, please post the full error message and I'll look closer.

**Comment by cybermancy** [comment]
> Hello
> 
> After extracting the SDK zip archive from [the steamworks page](https://partner.steamgames.com/doc/sdk) the resulting folder should be just called `sdk/`. You can point to the right directory with the command `$ export STEAM_SDK_LOCATION=$HOME/Downloads/sdk` (assuming you unzipped the sdk to the Downloads directory).
> 
> After this (and possibly a `cargo clean`) everything should work seamlessly. If you have more trouble, please post the full error message and I'll look closer.

This was actually the first thing I tried but no dice.

**Comment by Noxime** [comment]
Solved in DM's; The build problems were caused by the SDK location env var being incorrect. Make sure it points to the `sdk/` path if you encounter a similar issue
