### ISSUE TITLE
sdk 1.51 build failed in mac vm

### ISSUE THREAD

**Issue by alexheretic** [Noxime/steamworks-rs#52]
Build script is failing with a bunch of errors like

```
.../public/steam/steam_api_common.h:227:54: error: use of undeclared identifier 'nullptr'
```

**Comment by Noxime** [comment]
Can you tell me more about your setup. What version of MacOS are you running, are you on Apple Silicon? From my knowledge this error is more related to a broken C toolchain rather than anything to do with steamworks-rs specifically.

**Comment by alexheretic** [comment]
Sorry yeah that info was a bit sparse. It's a VM running **10.15.7**, I raised the issue as it has been working fine for a while so I was hoping for a quick answer.

I'll try to reinstall my llvm/clang bits and see if that helps.

**Comment by alexheretic** [comment]
Ok I installed llvm with brew and added the local llvm/bin to $PATH, plus set $LDFLAGS & $CPPFLAGS as suggested by brew installer.

It seems to build again thanks :+1:. I guess it was working before with the system llvm, as it looks like I hadn't brew-ed it.
