### ISSUE TITLE
No SetStat function

### ISSUE THREAD

**Issue by Epacnoss** [Noxime/steamworks-rs#77]
Am I missing something stupid?
I was looking through the [Step-by-Step guide](https://partner.steamgames.com/doc/features/achievements/stats_guide) for stats, and I couldn't find SteamUserStats()->SetStat(name, value) anywhere...

**Comment by Epacnoss** [comment]
Looking through the bindings with grep, bindgen seems to be working:

./steamworks-sys/src/bindings.rs:25639:    pub fn SteamAPI_ISteamUserStats_SetStatInt32(
./steamworks-sys/src/bindings.rs:25646:    pub fn SteamAPI_ISteamUserStats_SetStatFloat(

**Comment by Noxime** [comment]
Added in 9db7ac7, crates.io should be updated once I land #64
