### ISSUE TITLE
ERROR: thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by Gurigraphics** [Noxime/steamworks-rs#82]
I'm getting this error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitFailed', src\main.rs:14:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Code
```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]
use steamworks::AppId;
use steamworks::Client;
use steamworks::FriendFlags;
use steamworks::PersonaStateChange;

fn main() {
 
  println!("test");

  let (client, _single) = Client::init().unwrap();

  println!("test");
}
```

Did I forget something?

**Comment by ceifa** [comment]
The steam client initialization can fail for different reasons, you can check it on the official sdk documentation: https://partner.steamgames.com/doc/api/steam_api#SteamAPI_Init

People usually try to initialize it on the Space War game to check if it's a lib/sdk issue or a game/appid. You can do it calling `Client.init_app`:

```rust
Client::init_app(480);
```

**Comment by bazizi** [comment]
@Gurigraphics You need to create a `steam_appid.txt` file in the root directory whose contents is the AppID of the game.
