### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by Noxime** [Noxime/steamworks-rs#85]
Hello, since the start of the year I have been conscripted into the Finnish army and I will be serving my duty until September/October. This means my free time to maintain steamworks-rs has been effectively cut completely from the already low standard. While the crate is maintained quite passively, with features landing through (greatly appreciated) external PRs, I have no time to review and merge them anymore.

To fix this issue, we should either nominate a new maintainer or add acting co-maintainers to the project. I can return to maintainership when I move to the reserves, but until then we should find new people. If anyone is willing to step up, it'd be great for the Rust gamedev community! 

I've noticed at least @james7132 and @Nonakesh have been quite active on steamworks-rs, would either or both of you wish to take the mantle? No pressure, of course

**Comment by james7132** [comment]
I'm certainly available to help maintain the crate insofar as keeping it in sync with the published Steamworks SDK.

I maintain the wrapper around this library for integrating it into Bevy, and definitely want to see this kept up to date.

Hearing of your conscription is a bit concerning to hear in these trying times though.

**Comment by ceifa** [comment]
Hey, recently I started my own fork of steamworks-rs because of the lack of maintaining. I'm very active on github and I would be happy to be a co-maintainer, if needed.

**Comment by Noxime** [comment]
Thank you @james7132 and @ceifa, I have added you both as new collaborators to the repository. I will return to maintainership when I move into the reserves in the fall, but till then I will be quite inactive. 

(and do not worry about the conscription, it is a long tradition here and we do not intend to provoke any conflict with anyone, anytime :) )

**Comment by Nonakesh** [comment]
I am quite busy on a project myself, but I will likely contribute every few months. Also as I've made the NetworkingSockets wrapper I'd be happy to join any discussions regarding that.

**Comment by james7132** [comment]
@Noxime is it possible for you to give publish permissions for the crate to someone else while you're indisposed? I think we're seeing enough change that we should prep a 0.9 release.

**Comment by james7132** [comment]
@Noxime sorry to bother you again about this, but with the `v0.9.0`, I think we'll also need ownership of the `steamworks-sys` crate too.
